//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usersWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        

        public int productid { get; set; }
        public string productname { get; set; }
        public string productdescription { get; set; }

        public int boxid { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
