//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace usersWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wrapping
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public int RangeID { get; set; }
        public string RangeName { get; set; }
        public decimal Price { get; set; }
        public decimal Size { get; set; }
    }
}
